CONFIG_GPIO=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=49152

# Cryptography
CONFIG_CRYPTO=y
CONFIG_CRYPTO_NRF_ECB=y
#CONFIG_NORDIC_SECURITY_BACKEND=n
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=20480

CONFIG_MBEDTLS_RSA_C=y
CONFIG_MBEDTLS_PK_C=y
CONFIG_MBEDTLS_PK_PARSE_C=y
CONFIG_MBEDTLS_LEGACY_CRYPTO_C=y
CONFIG_MBEDTLS_PKCS1_V15=y
CONFIG_MBEDTLS_CTR_DRBG_C=y
CONFIG_MBEDTLS_ENTROPY_C=y

CONFIG_JWT=y
CONFIG_JWT_SIGN_RSA_PSA=y
CONFIG_BASE64=y

# Timer
CONFIG_NEWLIB_LIBC=y
CONFIG_POSIX_API=y
#CONFIG_POSIX_CLOCK=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_NEWLIB_LIBC_FLOAT_SCANF=y
# do we need this when we have printf float??
CONFIG_CBPRINTF_FP_SUPPORT=y

# AT Client Sample Configuration
# Logging
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
#CONFIG_UART_CONSOLE=y
# I use shell which also enables serial backend.
# Enabling it in two different modules caused log messages to be printed twice
#CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BUFFER_SIZE=16384


# Serial and UART
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_PIPE=y

# Modem subsystem
CONFIG_MODEM_MODULES=y
CONFIG_MODEM_BACKEND_UART=y
CONFIG_MODEM_PIPE=y
CONFIG_MODEM_CHAT=y

# Shell subsystem
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_SHELL_MINIMAL=y
# default stack size is 2048
#CONFIG_SHELL_STACK_SIZE=4096
CONFIG_SHELL_BACKEND_SERIAL=y
# Set my own prompt instead of the default
CONFIG_SHELL_PROMPT_UART="envi:~$ "

# Bluetooth
CONFIG_BT=y
CONFIG_BT_OBSERVER=y

# Enable Extended Scanning
CONFIG_BT_EXT_ADV=y
CONFIG_BT_EXT_SCAN_BUF_SIZE=1650

# Zephyr Bluetooth LE Controller needs 16 event buffers to generate Extended
# Advertising Report for receiving the complete 1650 bytes of data
CONFIG_BT_BUF_EVT_RX_COUNT=16

# the following two require BT_LL_SW_SPLIT, which is experimental and unknown to me
# Set maximum scan data length for Extended Scanning in Bluetooth LE Controller
#CONFIG_BT_CTLR_SCAN_DATA_LEN_MAX=1650

# Increase Zephyr Bluetooth LE Controller Rx buffer to receive complete chain
# of PDUs
#CONFIG_BT_CTLR_RX_BUFFERS=9

# NV storage
CONFIG_FLASH=y
CONFIG_NVS=y
CONFIG_NVS_DATA_CRC=y
#CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NVS_LOG_LEVEL_DBG=n
#CONFIG_REBOOT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

#debug
CONFIG_THREAD_ANALYZER=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_NAME=y
CONFIG_KERNEL_SHELL=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

CONFIG_SDI12=y
CONFIG_RUUVI_TAG=y
CONFIG_CLOUD_SEND_LORA=y